export interface LandCoverClass {
    id: string
    label: string
    color: string
}

// Complete list of 129 barangays in Baguio City
export const BAGUIO_BARANGAYS = [
    "Abanao-Zandueta-Kayong-Chugum",
    "Alfonso Tabora",
    "Ambiong",
    "Andres Bonifacio",
    "Apugan-Loakan",
    "Asin Road",
    "Atok Trail",
    "Aurora Hill Proper",
    "Aurora Hill, North Central",
    "Aurora Hill, South Central",
    "Bagong Lipunan (Market Area)",
    "Bakakeng Central",
    "Bakakeng North",
    "Bal-Marcoville (Marcoville)",
    "Balsigan",
    "Bayan Park East",
    "Bayan Park Village",
    "Bayan Park West (Bayan Park)",
    "BGH Compound",
    "Bonifacio-Caguioa-Rimando",
    "Brookside",
    "Brookspoint",
    "Cabinet Hill-Teacher's Camp",
    "Camdas Subdivision",
    "Camp 7",
    "Camp 8",
    "Camp Allen",
    "Campo Filipino",
    "City Camp Central",
    "City Camp Proper",
    "Country Club Village",
    "Cresencia Village Barangay",
    "Dagsian, Lower",
    "Dagsian, Upper",
    "Department of Public Services (DPS) Compound",
    "Dizon Subdivision",
    "Dominican Hill Mirador",
    "Dontogan",
    "Engineers' Hill",
    "Fairview Village",
    "Ferdinand (Happy Homes-Campo)",
    "Fort del Pilar",
    "Gabriela Silang",
    "General Emilio F. Aguinaldo",
    "General Luna, Lower",
    "General Luna, Upper",
    "Gibraltar",
    "Greenwater Village",
    "Guisad Central",
    "Guisad Sorong",
    "Happy Hollow",
    "Happy Homes (Happy Homes-Lucban)",
    "Harrison-Claudio Carantes",
    "Hillside",
    "Holy Ghost Extension",
    "Holy Ghost Proper",
    "Honeymoon (Honeymoon-Holy Ghost)",
    "Imelda R. Marcos (La Salle)",
    "Imelda Village",
    "Irisan",
    "Kabayanihan",
    "Kagitingan",
    "Kayang Extension",
    "Kayang-Hilltop",
    "Kias",
    "Legarda-Burnham-Kisad",
    "Liwanag-Loakan",
    "Loakan Proper",
    "Lopez Jaena",
    "Lourdes Subdivision Extension",
    "Lourdes Subdivision, Lower",
    "Lourdes Subdivision, Proper",
    "Lualhati",
    "Lucnab",
    "Magsaysay Private Road",
    "Magsaysay, Lower",
    "Magsaysay, Upper",
    "Malcolm Square-Perfecto",
    "Manuel A. Roxas",
    "Market Subdivision, Upper",
    "Middle Quezon Hill Subdivision",
    "Military Cut-off",
    "Mines View Park",
    "Modern Site, East",
    "Modern Site, West",
    "MRR-Queen Of Peace",
    "New Lucban",
    "Outlook Drive",
    "Pacdal",
    "Padre Burgos",
    "Padre Zamora",
    "Palma-Urbano",
    "Phil-Am",
    "Pinget",
    "Pinsao Pilot Project",
    "Pinsao Proper",
    "Pucsusan",
    "Puliwes",
    "Quezon Hill Proper",
    "Quezon Hill, Upper",
    "Quirino Hill, East",
    "Quirino Hill, Lower",
    "Quirino Hill, Middle",
    "Quirino Hill, West",
    "Quirino-Magsaysay, Upper",
    "Rizal Monument Area",
    "Rock Quarry, Lower",
    "Rock Quarry, Middle",
    "Rock Quarry, Upper",
    "Saint Joseph Village",
    "Salud Mitra",
    "San Antonio Village",
    "San Luis Village",
    "San Roque Village",
    "San Vicente",
    "Sanitary Camp South",
    "Sanitary Camp, North",
    "Santa Escolastica",
    "Santo Rosario Valley",
    "Santo Tomas Proper",
    "Santo Tomas School Area",
    "Scout Barrio",
    "Session Road Area",
    "Slaughter House Area",
    "SLU-SVP Housing Village",
    "South Drive",
    "Teodora Alonzo",
    "Trancoville",
    "Victoria Village",
] as const


// 9 land cover classes from Google's Dynamic World V1 (DWV1) dataset
// Colors based on official DWV1 color scheme
export const LAND_COVER_CLASSES: LandCoverClass[] = [
    { id: "water", label: "Water", color: "#419BDF" },
    { id: "trees", label: "Trees", color: "#397D49" },
    { id: "grass", label: "Grass", color: "#88B053" },
    { id: "flooded", label: "Flooded Vegetation", color: "#7A87C6" },
    { id: "crops", label: "Crops", color: "#E49635" },
    { id: "shrub", label: "Shrub & Scrub", color: "#DFC35A" },
    { id: "built", label: "Built-up Area", color: "#C4281B" },
    { id: "bare", label: "Bare Ground", color: "#A59B8F" },
    { id: "snow", label: "Snow & Ice", color: "#B39FE1" },
]

export const YEARS = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
