services:
  thesis_localstack:
    image: localstack/localstack:latest
    container_name: thesis_localstack
    ports:
      - '4566:4566'
    environment:
      # persist only what are specified
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- } # use .env or empty string
      - PERSISTENCE=1

    volumes:
      # persisted state stored here on host
      - './data/docker/my-localstack-data:/var/lib/localstack'

  thesis_database:
    image: postgres:15
    container_name: thesis_database
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes: 
      - './data/docker/my-postgres-data:/var/lib/postgresql/data'
